name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "AZemmanuel20" | docker login -u "messanemmanuel" --password-stdin

    - name: Generate timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Construire l'image Docker
      run: docker build . --file Dockerfile --tag messanemmanuel/backend:1.0.0

    - name: Pousser l'image Docker
      run: docker push messanemmanuel/backend:1.0.0