name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "AZemmanuel20" | docker login -u "messanemmanuel" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag messanemmanuel/backend

    - name: Push Docker image
      run: docker push messanemmanuel/backend